#!/bin/bash
# ==============================================
#     FSI TUTORIAL CLEANER - MULTIFLAP CASE
# ==============================================
# This script removes all generated files and simulation results
# to reset the case to a clean state.

echo "🧹 [CLEANUP] Cleaning multiflap FSI tutorial..."

# Remove preCICE runtime files and logs
echo "   • Removing preCICE runtime and logs..."
rm -rf precice-run
rm -rf *.log
rm -rf logs_archive

# Remove files generated by scripts/generate_all.py
echo "   • Removing generated configuration files..."

# Generated fluid files
rm -f fluid/system/blockMeshDict
rm -f fluid/system/controlDict
rm -f fluid/system/preciceDict

# Generated preCICE configuration
rm -f precice-config.xml

# Generated solid configuration  
rm -f solid/solid_config.yaml

# Clean fluid directory (OpenFOAM results)
echo "   • Cleaning fluid simulation results..."
cd fluid && ./clean.sh &> /dev/null
cd ..

# Clean solid directory (FEM results)
echo "   • Cleaning solid simulation results..."
cd solid && ./clean.sh &> /dev/null  
cd ..

# Remove any remaining generated files
echo "   • Removing other generated files..."
rm -f *.png
rm -f *.vtk
rm -f *.csv
rm -f *.dat

echo "✅ [CLEANUP] Tutorial cleaned successfully!"
echo "   Run 'python3 scripts/generate_all.py' to regenerate configuration files."
